name: "Flutter Build macOS"
description: "Compile l'application Flutter pour macOS"
inputs:
  flutter-version:
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
    - run: flutter pub get
    - run: flutter build macos
