name: "Manage Issues by Commit"
description: "Déplace les issues automatiquement selon les messages de commit (open/test/close #num)"

inputs:
  project-name:
    description: "Nom du projet GitHub Project"
    required: true
  column-open:
    description: "Nom de la colonne pour 'open'"
    required: true
  column-test:
    description: "Nom de la colonne pour 'test'"
    required: true
  column-close:
    description: "Nom de la colonne pour 'close'"
    required: true

runs:
  using: "node20"
  main: "entrypoint.js"