name: Actions de formatage
inputs:
  platform:
    description: "Plateforme cible"
    required: true
  mode:
    description: "Mode de compilation"
    required: true
runs:
  using: composite
  steps:
    #### Installer les dépendances nécessaires pour Linux si on build sur Linux ####
    - name: Installer les dépendances Linux
      shell: bash
      if: ${{ inputs.platform == 'linux' && inputs.mode == 'release'}}
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libglib2.0-dev

    #### Exécution de icônes installeur generator si Windows et release ####
    # Installer les dépendances Python nécessaires
    - name: Installer les dépendances Python
      shell: bash
      if: ${{ inputs.platform == 'windows' && inputs.mode == 'release' }}
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade Pillow
    # Exécuter le script Python pour générer les icônes de l'installeur
    - name: Exécuter icônes installeur generator
      shell: bash
      working-directory: assets/images
      if: ${{ inputs.platform == 'windows' && inputs.mode == 'release' }}
      run: python icon_instaleur_generator.py
