name: Package Release Build
inputs:
  platform:
    required: true
    description: "Plateforme cible"
runs:
  using: composite
  steps:
    # Packaging Windows
    - name: Install Inno Setup (Windows)
      if: ${{ inputs.platform == 'windows' }}
      shell: bash
      run: choco install innosetup -y

    - name: Format repo name for setup file name (Windows)
      id: format_name
      shell: pwsh
      run: |
        $repoName = "${{ github.event.repository.name }}"
        # Remplacer tout caractère non-alphanumérique par espace
        $tmp = ($repoName -replace '[^a-zA-Z0-9]', ' ')
        # Uppercase chaque "mot" et tout coller sans espace
        $safeName = ($tmp -split ' ' | ForEach-Object { if ($_.Length -gt 0) { $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower() } }) -join ''
        $setupName = "Setup$($safeName)"
        echo "setup_name=$setupName" >> $env:GITHUB_OUTPUT

    - name: Create Installer (Windows)
      if: ${{ inputs.platform == 'windows' }}
      shell: pwsh
      run: ISCC /DMyAppVersion="${{ github.ref_name }}" /DMyAppSetupName="${{ steps.format_name.outputs.setup_name }}" installer.iss

    - name: Archive windows build artifacts (Windows)
      if: ${{ inputs.platform == 'windows' }}
      uses: actions/upload-artifact@v4
      with:
        name: flutter-build-windows
        path: installer/output/${{ steps.format_name.outputs.setup_name }}.exe

    # Packaging Linux
    - name: Archive Linux bundle (Linux)
      if: ${{ inputs.platform == 'linux' }}
      shell: bash
      run: tar -czf flutter-linux.tar.gz -C build/linux/x64/release/bundle .
    - name: Upload Linux artifact (Linux)
      if: ${{ inputs.platform == 'linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: flutter-build-linux
        path: flutter-linux.tar.gz

    # Packaging MacOS
    # todo: Ajouter les étapes de packaging pour MacOS
    # Packaging APK
    # todo: Ajouter les étapes de packaging pour APK
    # Packaging iOS
    # todo: Ajouter les étapes de packaging pour iOS
    # Packaging Web
    # todo: Ajouter les étapes de packaging pour Web
