name: "Flutter Build Web"
description: "Compile l'application Flutter en Web App (HTML/CSS/JS)"
inputs:
  flutter-version:
    required: false
    default: "stable"

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
    - run: flutter pub get
    - run: flutter build web
