name: Bump Version
inputs:
  bump:
    description: "major, minor, patch, build, pre(avant-première), breaking (y->0.y.z et x->x.y.z), release"
    required: true
outputs:
  version:
    description: "nouvelle version après le bump"
    value: ${{ steps.extract_version.outputs.version }}
runs:
  using: composite
  steps:
    - id: extract_version
      shell: bash
      run: dart pub global run cider bump ${{ inputs.bump }}

    - name: Générer le changelog et préparer la release
      if: ${{ inputs.bump == 'release' }}
      shell: bash
      run: cider release

    - name: Extract the new version from pubspec.yaml
      shell: bash
      run: |
        VERSION=$(dart pub global run cider version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
