name: Bump Version
description: "Met à jour la version de l'application en fonction du nom de la branche"
inputs:
  branch_name:
    description: "Nom de la branche actuelle"
    required: true
outputs:
  version:
    description: "nouvelle version après le bump"
    value: ${{ steps.extract_version.outputs.version }}
runs:
  using: composite
  steps:
    - name: bump en fonction de branch_name
      shell: bash
      run: |
        if ${{ contains( inputs.branch_name , 'release') }}; then
          echo "Bumping version for release branch"
          dart pub global run cider bump minor 
        elif ${{ contains( inputs.branch_name , 'fix') }}; then
          echo "Bumping version for fix branch"
          dart pub global run cider bump patch 
        elif ${{ contains( inputs.branch_name , 'feature') }}; then
          echo "Bumping version for feature branch"
          dart pub global run cider bump build 
        else
          echo "No version bump needed for this branch"
          exit 0
        fi

    - name: Extract the new version from pubspec.yaml
      shell: bash
      run: |
        VERSION=$(dart pub global run cider version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
