name: Flutter CI

# Déclenche le workflow sur les pull_request
# pour les branches spécifiées : main, dev** et release/**
on:
  pull_request:
    branches:
      - main
      - dev**
      - release/**
  workflow_dispatch: # Tu peux aussi le lancer manuellement depuis l'interface GitHub

jobs:
  # Dans un premier temps on fait l'analyse du code et les tests unitaires
  Analyse-et-tests:
    uses: Theobernardon/theo-flutter/.github/workflows/test-flutter.yml@main

  Builds:
    uses: Theobernardon/theo-flutter/.github/workflows/builds.yml@main
    with:
      # Liste des plateformes à builder
      platforms: windows, linux, macos, apk, ios, web
